/** @format */

export interface OrdererEnvs {
	ORDERER_ID?: string
	ORDERER_CA?: string
	ORDERER_GENERAL_LISTENADDRESS?: string
	ORDERER_GENERAL_LISTENPORT?: string
	ORDERER_GENERAL_LOCALMSPID?: string
	ORDERER_GENERAL_LOCALMSPDIR?: string
	ORDERER_GENERAL_TLS_ENABLED?: string
	ORDERER_GENERAL_TLS_ROOTCAS?: string
	ORDERER_GENERAL_TLS_PRIVATEKEY?: string
	ORDERER_GENERAL_TLS_CERTIFICATE?: string
}

export interface PeerEnvs {
	PATH?: string
	FABRIC_CFG_PATH?: string
	CORE_PEER_ID?: string
	CORE_PEER_ADDRESS?: string
	CORE_PEER_LOCALMSPID?: string
	CORE_PEER_MSPCONFIGPATH?: string
	CORE_PEER_TLS_ENABLED?: string
	CORE_PEER_TLS_ROOTCERT_FILE?: string
	CORE_PEER_TLS_CERT_FILE?: string
	CORE_PEER_TLS_KEY_FILE?: string
}
